--- 
title: "Biology 125 Summer Lab Manual"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
description: "Your Description Here"
---

# Welcome {-}

To your Biology 125 Labs!

**First**, a few important and relevant links...

* [Canvas course shell](https://canvas.ubc.ca/courses/90148)
* [Syllabus](https://canvas.ubc.ca/courses/90148/assignments/syllabus)

**Second**, some key pieces of information for how labs will be run this term...

The following pages detail how labs, assignments, and absences will be handled. In addition to the content here, the lab manual, assignments, quizzes, and additional resources are all supplied on Canvas so take some time to look over the information.

If in doubt about course policies, refer to your syllabus or talk to your TA. To get started read through your course syllabus and the lab manual. 

Above all, have fun this term and enjoy the process of science!

Sincerely,

Dr. Tristyn Hay

## Labs {-}

Similar to term 1, labs will be alternating between on-campus and online, with some online labs being conducted in Zoom during your regular scheduled lab section. In order to be successful this term please pay attention to your syllabus where you can find your schedule, mark breakdown, missed lab policy, and all lab requirements for your BIOL125 lab. You will need the information found in this syllabus to be able to answer the Introductory Quiz on canvas. Students will not be excused of any missed or late assignments due to being \"unaware\" of these policies so be sure you reference this information often. 

Your first lab, Lab 1, is synchronous - meaning that you complete it on-campus - with the relevant material being posted on Canvas. You will have the opportunity to meet your TA and the other students registered in your lab section. This week will be a very important week as you will have your partner assigned to you and will be setting up for an experiment. For in-person labs, it is vital that you attend the lab for which you are registered - check your registration online to be sure of where you are supposed to be!

Your second lab, Lab 2, will be asynchronous - meaning you will work on it in your own time and online. Your TA will be available online during your regular scheduled lab sections if you have any questions or concerns.

During the synchronous labs you may bring a lab coat but this is not required. Closed toed shoes and pants are required for this lab and your TA will turn you away if you are not in proper attire. Any goggles and gloves will be provided in lab. 

## Assignments {-}

See Canvas for due dates.

All assignments, even those worked on as a group, will need to be submitted individually unless directed to do so by your TA.

Failure to submit an assignment will result in a mark of 0 for that assignment. No exceptions!

Please be sure you have not only submitted assignments on time but that you have double-checked they have been uploaded properly.

## Absences {-}

Pay attention to your absence scores - see syllabus for details. Students receiving an absence score over 5 will fail the lab. This applies to both on campus and online assignments. If an assignment is not submitted it counts as an absence. Excused absences get a score of 1 and unexcused a score of 2.5.

Absences can only be excused by myself (Dr. Hay) and not your TA.

## Copyright {-}

This work is licenced under the Creative Commons [Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/)

Please use the following for citing this document

Hay, T., Vis-Dunbar, M. (2021). *Biology 125 Lab Manual*. [https://ubco-biology.github.io/BIOL-125-Lab-Manual/](https://ubco-biology.github.io/BIOL-125-Lab-Manual/)

All source files are available [https://github.com/ubco-biology/BIOL-125-Lab-Manual](https://github.com/ubco-biology/BIOL-125-Lab-Manual).

## UBCO Biology open materials {-}

This resource is part of a larger project to host UBCO Biology lab materials in an open, accessible format.

All BIOL open materials can be found at [https://ubco-biology.github.io/](https://ubco-biology.github.io/)

## Conventions {-}

<div class = "flag">
Information relevant to lab logistics and grading.
</div>

<div class = "note">
Further insights or notes on presented materials.
</div>

<div class = "takeAway">
Highlights and key take aways.
</div>

<div class = "advanced">
Optional material that dives deeper into a presented concept.
</div>

